// this file is generated by compiler
process.env.SUMMER_ENV = "prod"
import * as defaultConfig from "./config/default.config"
global["$$_DEFAULT_CONFIG"] = defaultConfig
import '@summer-js/swagger'
import './controller/HelloController'
